<a href="https://colab.research.google.com/github/Amin1218/Big_data/blob/main/Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
result = 0
for i in range(100):
  result += i
  print(result)


0
1
3
6
10
15
21
28
36
45
55
66
78
91
105
120
136
153
171
190
210
231
253
276
300
325
351
378
406
435
465
496
528
561
595
630
666
703
741
780
820
861
903
946
990
1035
1081
1128
1176
1225
1275
1326
1378
1431
1485
1540
1596
1653
1711
1770
1830
1891
1953
2016
2080
2145
2211
2278
2346
2415
2485
2556
2628
2701
2775
2850
2926
3003
3081
3160
3240
3321
3403
3486
3570
3655
3741
3828
3916
4005
4095
4186
4278
4371
4465
4560
4656
4753
4851
4950


In [ ]:
L = list(range(10))
L

In [ ]:
type([0])

list

In [ ]:
L2 = [str(c) for c in L]
type(L2)

list

In [ ]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [ ]:
import array

L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
np.zeros (10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.random.normal(0, 1, (3,3))

array([[-1.069542  , -0.23010162, -0.01300653],
       [-0.25999565,  0.96356433, -1.23438619],
       [-0.03827431, -0.04680178, -0.65946303]])

In [ ]:
np.random.randint(0, 10, (3, 3))

array([[7, 5, 0],
       [3, 6, 4],
       [8, 2, 3]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty(3)

array([1., 1., 1.])

In [ ]:
np.zeros(10,dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

Home work 

In [ ]:
import numpy as np
np.random.seed(0) # seed for reproducttibility 

In [ ]:
x1 = np.random.randint(10, size=6) # One dimentional array

In [ ]:
x2 = np.random.randint(10, size=(3, 4)) #Two-dimentional array 

In [ ]:
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimentional array

In [ ]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

NameError: ignored

In [ ]:
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

NameError: ignored

In [ ]:
x1
x1[0]
x1[4]
x1[-1]
x1[-2]

2

In [ ]:
x2
x2[0, 0]
x2[2, 0]
x2[2, -1]


9

In [ ]:
x2[0, 0]
print(x2)

[[2 3 9 7]
 [5 3 4 5]
 [3 3 7 9]]


In [ ]:
x1[0]=3.141159
print(x1)

[3 9 7 3 2 3]


In [ ]:
x =np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x[:5] # first five elements 

array([0, 1, 2, 3, 4])

In [ ]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7] # middle sub-array 

array([4, 5, 6])

In [ ]:
x[::2] #every other elements

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2] # every other elements, starting at index 1

array([1, 3, 5, 7, 9])

In [ ]:
x[::-1] #all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::2] # reversed every other from index 5

array([5, 7, 9])

In [ ]:
print(x2)
x2[:2, :3] # two rows, three columns

[[2 3 9 7]
 [5 3 4 5]
 [3 3 7 9]]


array([[2, 3, 9],
       [5, 3, 4]])

In [ ]:
x2[:3, ::2]

array([[2, 9],
       [5, 4],
       [3, 7]])

In [ ]:
x2[::-1, ::-1] # ??

array([[9, 7, 3, 3],
       [5, 4, 3, 5],
       [7, 9, 3, 2]])

In [ ]:
print(x2[:, 0]) # First colum of x2

[2 5 3]


In [ ]:
print(x2[0, :]) # First row of x2

[2 3 9 7]


In [ ]:
print (x2[0]) #equivalant to x2[0, :]

[2 3 9 7]


In [ ]:
x2_sub_copy = x2[:2, :2].copy() #Creating copies of arrays
print(x2_sub_copy)

[[2 3]
 [5 3]]


In [ ]:
grid =np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x  = np.array([1,2,3]) 
x.reshape((1,3)) #row vector via reshape
x[np.newaxis, :] # row vector via newaxis
x.reshape((3,1)) # column vector via reshape
x[:, np.newaxis] # column vector via newaxis


array([[1],
       [2],
       [3]])

In [ ]:
# Concatenation of array
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
# Concatenation more then two array
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [ ]:
x = np.array ([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5,4]])
np.vstack([x, grid]) #vertically stack the arrrays

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
# Splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print (x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
import numpy as np      # ??
name = ['Alice','Bob','Cathy','Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]
x = np.zeros(4, dtype=int)

In [ ]:
# Use a compound data type for structured arrays

data = np.zero(4, dtype={'names':('name','age','weight'),
                        'formats':('U10','i4','f8')})
print(data.dtype)

AttributeError: ignored

In [ ]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)


NameError: ignored

In [ ]:
# Get all names
data['name']

# Get first row of data
data[0]

#Get the name from the last row
Data[-1]['name']

#Get names where age is under 30
data[data['age']<30]['name']

NameError: ignored

In [ ]:
# Creating Structured Arrays
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4','f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [ ]:
np.dtype({'names':('name','age','weigt'),
          'formats':((np.str_,10), int,np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weigt', '<f4')])

In [ ]:
np.dtype({'names':('name','age','weig'})